# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Loop-Gtk2
version:      0.0026
version_from: lib/POE/Loop/Gtk2.pm
installdirs:  site
requires:
    Gtk2:                          0
    POE:                           0.30
    POE::Loop::Glib:               0.00022

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
